name: Automatic Rebase
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  rebase:
    permissions:
      contents: write  # for Git to git push
    name: Rebase `dependencies` with `master`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: dependencies
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/master
          git push origin dependencies --force
